07input
js-tasks-ru/htmlcss-20211125_gennadiy8 pull request #10
Opened 2021-12-17 20:58 UTC by gennadiipetrov

2021-12-17 20:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-17 21:10 UTC, GSemikozov requested changes

2021-12-17 21:10 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    margin: 12px;
только слева надо

2021-12-17 21:10 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    border-radius: 4px;
уже определен выше, не нужно дублировать

2021-12-17 21:10 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    border-radius: 16px;
уже задано

2021-12-17 21:10 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    transform: translate(23px);
translateX? или и Y тоже?

2021-12-17 21:10 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    padding: 5px;
кажется лишнее

2021-12-17 21:10 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    position: relative;
не обязателное

2021-12-17 21:10 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    padding-bottom: 13px;
а как же справа, там где будет иконка?

2021-12-17 21:10 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.textbox__icon {
видимо лишнее

2021-12-18 16:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-18 16:59 UTC, gennadiipetrov commented on 07-lection5/01-checkbox/checkbox.css
> +    margin: 12px;
исправлено

2021-12-18 17:02 UTC, gennadiipetrov commented on 07-lection5/01-checkbox/checkbox.css
> +    border-radius: 4px;
исправлено

2021-12-18 17:02 UTC, gennadiipetrov commented on 07-lection5/03-toggler/toggler.css
> +    border-radius: 16px;
исправлено

2021-12-18 17:03 UTC, gennadiipetrov commented on 07-lection5/03-toggler/toggler.css
> +    transform: translate(23px);
translateX

```
transform: translate(tx);
transform: translate(tx, ty);
```

2021-12-18 17:05 UTC, gennadiipetrov commented on 07-lection5/04-input/input.css
> +    padding: 5px;
исправлено

2021-12-18 17:12 UTC, gennadiipetrov commented on 07-lection5/04-input/input.css
> +    position: relative;
исправлено.

2021-12-18 17:16 UTC, gennadiipetrov commented on 07-lection5/04-input/input.css
> +.textbox__icon {
исправлено

2021-12-18 17:18 UTC, gennadiipetrov commented on 07-lection5/04-input/input.css
> +    padding-bottom: 13px;
добавил. но тут есть один момент я позиционарирование иконки сделал через ` background-position-x: 95%;` и `padding-right `не оказывает влияние на иконку.

2021-12-18 17:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-18 17:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-18 19:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-19 19:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-21 17:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-21 17:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-21 19:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-23 19:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-23 19:39 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    padding-bottom: 13px;
на иконку и не будет, а вот на текст в инпуте - вполне) смысл в том, чтобы не случилось так что при валидации иконка перекроет собой текст

2021-12-24 17:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-24 17:31 UTC, gennadiipetrov commented on 07-lection5/04-input/input.css
> +    padding-bottom: 13px;
ааа понял, чтобы такого не было 
![image](https://user-images.githubusercontent.com/77464892/147367089-f3c361f2-67d8-49fe-8609-b516d69edf15.png)

2021-12-24 17:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-24 18:40 UTC, GSemikozov approved these changes

2021-12-24 18:41 UTC, merged