feat(burger): added burger
js-tasks-ru/htmlcss-20211125_gennadiy8 pull request #11
Opened 2021-12-24 19:17 UTC by gennadiipetrov

2021-12-24 19:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-25 13:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-25 16:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-26 11:05 UTC, GSemikozov requested changes

2021-12-26 11:05 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +        transition: transform 300ms linear;
надо указать сразу на .burger-menu

2021-12-26 11:05 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +        top: 0;
top + left можно сразу указать в .burger-menu__checkbox-input, а при изменении состоянии менять только opacity. поэтому здесь и ниже - надо подчистить стили

2021-12-29 19:35 UTC, gennadiipetrov commented on 09-lection7/01-burger-menu/burger-menu.css
> +        transition: transform 300ms linear;
исправлено

2021-12-29 19:35 UTC, gennadiipetrov commented on 09-lection7/01-burger-menu/burger-menu.css
> +        top: 0;
исправлено

2021-12-29 19:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-29 19:44 UTC, GSemikozov approved these changes

2021-12-29 19:44 UTC, merged