feat(05calendar): added calendar and new fonts
js-tasks-ru/htmlcss-20211125_gennadiy8 pull request #6
Opened 2021-12-08 18:54 UTC by gennadiipetrov

2021-12-08 18:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-08 20:39 UTC, GSemikozov requested changes

2021-12-08 20:39 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.inter-paragraph-20w {
эти текстовые блоки описаны как независимые блоки, но в файле блока .calendar может быть только собственно .calendar + его элементы и модификаторы.
я бы советовал не выделять эти текстовые блоки, лучше инкапсулировать в соответствующих элементах календаря

2021-12-08 20:39 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    --calendar-item-color: #334D6E;
такой цвет. у нас уже есть в переменных - это один из основных цветов. Не стоит создавать переменные для значений которые уже записаны в глобальные переменные

2021-12-11 14:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-11 15:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-11 15:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-11 15:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-11 15:38 UTC, gennadiipetrov commented on 05-lection3/03-calendar/calendar.css
> +    --calendar-item-color: #334D6E;
![image](https://user-images.githubusercontent.com/77464892/145682369-90a2c13f-5289-4517-aee3-8d10002f9561.png)
![image](https://user-images.githubusercontent.com/77464892/145682376-34bfb6ef-f14e-4c68-92e5-4eff4600c5da.png)

2021-12-11 15:38 UTC, gennadiipetrov commented on 05-lection3/03-calendar/calendar.css
> +    --calendar-item-color: #334D6E;
не могу найти, а что за цвет?

2021-12-11 15:40 UTC, gennadiipetrov commented on 05-lection3/03-calendar/calendar.css
> +.inter-paragraph-20w {
я тут смиксовать атомик css с бэмом.

2021-12-11 15:48 UTC, gennadiipetrov commented on 05-lection3/03-calendar/calendar.css
> +.inter-paragraph-20w {
исправил

2021-12-11 15:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-13 15:01 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    --calendar-item-color: #334D6E;
можно брать blue-1

2021-12-14 19:28 UTC, GSemikozov approved these changes

2021-12-14 19:28 UTC, merged